[tool.poetry]
name = "pycounts_jbar"
version = "0.1.0"
description = "Count words in a text"
authors = ["Jeremy Barbier"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
